name: Generate SVG List

on:
  push:
    branches:
      - main
  workflow_dispatch: # Enable manual triggering

jobs:
  generate-svg-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: List SVG files
        run: |
          find ./public/svgs -name "*.svg" > svg-list.txt

      - name: Convert list to JSON
        run: |
          sudo apt-get install -y jq
          jq -R -s -c 'split("\n") | map(select(. != ""))' svg-list.txt > public/svg-files.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add svg-list.txt public/svg-files.json
          git commit -m "Update SVG files list"
          git push



